### ISSUE TITLE
构造器 FlutterView.FlutterView(Context,RenderMode)不适用 是否是Flutter版本问题

### ISSUE THREAD

**Issue by FightLi1017** [yuewen/mix_stack#1]
/Users/XXXXX/AndroidGroup/mix_stack/android/src/main/java/com/yuewen/mix_stack/component/MXFlutterView.java:47: 错误: 对于FlutterView(Context,FlutterTextureView), 找不到合适的构造器
        super(context, flutterTextureView);
        ^
    构造器 FlutterView.FlutterView(Context,RenderMode)不适用
      (参数不匹配; FlutterTextureView无法转换为RenderMode)
    构造器 FlutterView.FlutterView(Context,TransparencyMode)不适用
      (参数不匹配; FlutterTextureView无法转换为TransparencyMode)
    构造器 FlutterView.FlutterView(Context,AttributeSet)不适用
      (参数不匹配; FlutterTextureView无法转换为AttributeSet)

[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/lichenxi/flutter
    • Framework revision f139b11009 (10 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

**Comment by VomPom** [comment]
> /Users/XXXXX/AndroidGroup/mix_stack/android/src/main/java/com/yuewen/mix_stack/component/MXFlutterView.java:47: 错误: 对于FlutterView(Context,FlutterTextureView), 找不到合适的构造器
> super(context, flutterTextureView);
> ^
> 构造器 FlutterView.FlutterView(Context,RenderMode)不适用
> (参数不匹配; FlutterTextureView无法转换为RenderMode)
> 构造器 FlutterView.FlutterView(Context,TransparencyMode)不适用
> (参数不匹配; FlutterTextureView无法转换为TransparencyMode)
> 构造器 FlutterView.FlutterView(Context,AttributeSet)不适用
> (参数不匹配; FlutterTextureView无法转换为AttributeSet)
> 
> [✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
> • Flutter version 1.12.13+hotfix.9 at /Users/lichenxi/flutter
> • Framework revision f139b11009 (10 months ago), 2020-03-30 13:57:30 -0700
> • Engine revision af51afceb8
> • Dart version 2.7.2

请尝试使用 Flutter version >= 1.17.5 的稳定版本
