### ISSUE TITLE
Multiple Tab support 点击Flutter1 tab，去到后台再回到前台就崩溃

### ISSUE THREAD

**Issue by HXiaoMing** [yuewen/mix_stack#5]
步骤：
1.打开demo 点击 Multiple Tab support
2.点击底部的tab   Flutter1
3.去到后台，再回到前台
结果：崩溃

**Comment by pepsin** [comment]
这是 Android 上复现的问题吗 @HXiaoMing

**Comment by HXiaoMing** [comment]
嗯嗯

**Comment by VomPom** [comment]
> 嗯嗯

方便提供一下 手机型号、Flutter 所使用的版本信息，如有崩溃的堆栈信息更好，谢谢。
