### ISSUE TITLE
不兼容的类型: Activity无法转换为ExclusiveAppComponent<Activity>

### ISSUE THREAD

**Issue by hlovingness** [yuewen/mix_stack#7]
![image](https://user-images.githubusercontent.com/16331459/168119003-99460468-d052-4767-bc0a-47fe3cd2c500.png)

**Comment by pepsin** [comment]
对应的 Flutter 版本和 Android target version 是什么呢?

**Comment by hlovingness** [comment]
> 对应的 Flutter 版本和 Android target version 是什么呢?
```
Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1706], locale zh-CN)
compileSdkVersion 32
targetSdkVersion 30
```

**Comment by wragony** [comment]
问题我已经修复，等待作者merge
